const fs=require('fs');
const {ShellEyeClient}=require('../../program-host/sdk/client');
const results='C:/SHELLeye/Temp/results';fs.mkdirSync(results,{recursive:true});
(async()=>{const c=new ShellEyeClient();const q=(m,p={},t=30000)=>c.request(m,p,t);let cleanup={};try{
 const machine=await q('machine.inspect');const session=await q('session.inspect');const volume=await q('volume.inspect',{drive:'C:'});
 const workspace=`C:/SHELLeye/Temp/milestone-b-${Date.now()}`;const dir=await q('directory.create',{path:workspace});const file=await q('file.create',{path:`${workspace}/config.json`,content:'{"value":1}'});const file0=await q('file.inspect',{fileId:file.id});
 const cursor0=(await q('world.cursor')).cursor;const job=await q('job.create');const node='C:/AgentBrowser/tools/node-v24.18.1-win-x64/node.exe';const launch=await q('job.start',{jobId:job.id,executable:node,args:['X:/SHELLeye/repo/tests/fixtures/PersistentWorkload/server.js','--config',file.path,'--port','0'],cwd:'X:/SHELLeye/repo'});
 const readyWait=await q('job.wait_output',{jobId:job.id,contains:'"type":"ready"',timeoutMs:15000},20000);const ready=JSON.parse(readyWait.record.text.trim());await q('job.wait_member_count',{jobId:job.id,atLeast:2,timeoutMs:15000},20000);const members=await q('job.members',{jobId:job.id});const root=await q('process.inspect',{processId:launch.process.id});const child=members.members.find(x=>x.pid===ready.childPid);if(!child)throw new Error('fixture child was not resolved');const childInspect=await q('process.inspect',{processId:child.processId});
 const listener=await q('network.wait_listener',{address:'127.0.0.1',port:ready.port,ownerProcessId:launch.process.id,timeoutMs:10000},15000);const service=await q('service.inspect',{name:'EventLog'});
 const freshFile=await q('file.inspect',{fileId:file.id});const baseline=freshFile.revisionToken;const updated=await q('file.write',{fileId:file.id,content:'{"value":2,"changed":true}',expectedRevision:baseline});const fileWait=await q('file.wait_change',{fileId:file.id,baselineRevision:baseline,timeoutMs:5000},10000);
 const nodeClient=await q('process.start',{executable:node,args:['X:/SHELLeye/repo/tests/fixtures/PersistentWorkload/client.js',`http://127.0.0.1:${ready.port}/`],cwd:'X:/SHELLeye/repo'});const clientWait=await q('process.wait',{processId:nodeClient.process.id,timeoutMs:15000},20000);const clientResult=await q('process.result',{processId:nodeClient.process.id,timeoutMs:5000},10000);if(clientResult.exitCode!==0)throw new Error('direct client failed');
 const output2=await q('job.output',{jobId:job.id,afterCursor:readyWait.cursor,maxBytes:65536});const delta=await q('world.delta',{afterCursor:cursor0,limit:200});const sync=await q('world.sync');
 const types=[...new Set(delta.deltas.map(x=>x.type))];if(!types.includes('file.changed')||!types.includes('process.exited'))throw new Error('required compact deltas missing');if(root.sessionId!==session.sessionId)throw new Error('process->session relation wrong');if(listener.ownerProcessId!==launch.process.id)throw new Error('listener->process relation wrong');if(service.pid&&service.processId==null)throw new Error('service current PID did not resolve to proc_*');
 const result={passed:true,completedUtc:new Date().toISOString(),concepts:{machine:machine.machineId,session:session.id,volume:volume.id,directory:dir.id,file:file.id,job:job.id,rootProcess:launch.process.id,childProcess:child.processId,listener:listener.id,service:service.id,command:nodeClient.commandId},relationships:{processToSession:root.sessionId===session.sessionId,jobMemberCount:members.members.length,childParent:{id:childInspect.parent.processId,quality:childInspect.parent.quality},listenerOwner:listener.ownerProcessId,serviceProcess:service.processId,fileVolume:file.volumeId},waits:{jobMembers:true,file:fileWait,clientExit:clientWait},delta:{from:cursor0,to:delta.cursor,count:delta.deltas.length,types},output:{initialCursor:readyWait.cursor,afterCursor:output2.cursor,newRecordCount:output2.records.length},sync,payloadDiscipline:{fullProcessTableSurfaced:false,fullServiceTableSurfaced:false,fullTcpTableSurfaced:false,directoryDumpUsedForRoutineObservation:false}};
 fs.writeFileSync(`${results}/milestone-b.json`,JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 try{await q('job.terminate',{jobId:job.id});await q('job.wait_empty',{jobId:job.id,timeoutMs:10000},15000);await q('network.wait_absent',{address:'127.0.0.1',port:ready.port,listenerId:listener.id,timeoutMs:10000},15000);cleanup.job=true}catch(e){cleanup.jobError={code:e.code,message:e.message}}
 try{await q('file.delete',{fileId:file.id});cleanup.file=true}catch(e){cleanup.fileError={code:e.code,message:e.message}}try{await q('file.delete',{fileId:dir.id});cleanup.directory=true}catch(e){cleanup.directoryError={code:e.code,message:e.message}}result.cleanup=cleanup;fs.writeFileSync(`${results}/milestone-b.json`,JSON.stringify(result,null,2));
 }finally{await c.close();}})().catch(e=>{console.error(e.stack||String(e));process.exit(1)});


