const fs=require('fs');
const {ShellEyeClient,sdk}=require('../sdk');
const {raw}=require('../sdk/raw');
const results='C:/SHELLeye/Temp/results';fs.mkdirSync(results,{recursive:true});
(async()=>{
 const client=new ShellEyeClient();await client.connect();const s=sdk(client),r=raw(client);let count=0;const trace=[];
 const op=async(name,fn)=>{const t=Date.now();const value=await fn();count++;trace.push({n:count,name,ms:Date.now()-t});return value;};
 let cleanup={};
 try{
  const hello=await op('rpc.hello',()=>s.rpc.hello());
  const machine=await op('machine.inspect',()=>s.machine.inspect());
  const session=await op('session.inspect',()=>s.session.inspect());
  const volume=await op('volume.inspect.C',()=>s.volume.inspect('C:'));
  const workspace=`C:/SHELLeye/Temp/milestone-d-${Date.now()}`;
  const dir=await op('directory.create',()=>s.directory.create(workspace));
  const file=await op('file.create',()=>s.file.create(`${workspace}/config.json`,'{"generation":1}'));
  let fileInspect=await op('file.inspect.identity',()=>s.file.inspect(file.id));
  if(!fileInspect.continuity?.journalId)throw new Error('C: file continuity token absent');
  const world0=await op('world.cursor',()=>s.world.cursor());
  const job=await op('job.create',()=>s.job.create());
  const node='C:/AgentBrowser/tools/node-v24.18.1-win-x64/node.exe';
  const first=await op('job.start.first',()=>s.job.start(job.id,node,['X:/SHELLeye/repo/tests/fixtures/PersistentWorkload/server.js','--config',file.path,'--port','0'],'X:/SHELLeye/repo'));
  const ready1Wait=await op('job.wait_output.ready.first',()=>s.job.waitOutput(job.id,'"type":"ready"',null,15000));
  const ready1=JSON.parse(ready1Wait.record.text.trim());
  await op('job.wait_members.first',()=>s.job.waitMembers(job.id,2,15000));
  const members1=await op('job.members.first',()=>s.job.members(job.id));
  const root1=await op('process.inspect.first.root',()=>s.process.inspect(first.process.id));
  const child1row=members1.members.find(x=>x.pid===ready1.childPid);if(!child1row)throw new Error('declared first child missing');
  const child1=await op('process.inspect.first.child',()=>s.process.inspect(child1row.processId));
  const listener1=await op('network.wait_listener.first',()=>s.network.waitListener('127.0.0.1',ready1.port,first.process.id,10000));
  await op('listener.inspect.first',()=>s.listener.inspect(listener1.id));
  const clientProc=await op('process.start.client',()=>s.process.start(node,['X:/SHELLeye/repo/tests/fixtures/PersistentWorkload/client.js',`http://127.0.0.1:${ready1.port}/`],'X:/SHELLeye/repo'));
  const clientWait=await op('process.wait.client',()=>s.process.wait(clientProc.process.id,15000));
  const clientResult=await op('process.result.client',()=>s.process.result(clientProc.process.id,5000));if(clientResult.exitCode!==0)throw new Error('typed direct client failed');
  const ps=await op('powershell.invoke.structured',()=>s.powershell.invoke('Get-Process',{Id:first.process.pid},['Id','ProcessName','WorkingSet64']));if(!ps.structured||!ps.objects?.[0]?.typeNames?.length)throw new Error('PowerShell result was not a structured PSObject projection');
  const resources=await op('process.resources.first',()=>s.process.resources(first.process.id));
  const output1=await op('job.output.after-ready',()=>s.job.output(job.id,ready1Wait.cursor,65536));
  fileInspect=await op('file.inspect.before-write',()=>s.file.inspect(file.id));
  const changed=await op('file.write.guarded',()=>s.file.write(file.id,'{"generation":2,"changed":true}',fileInspect.revisionToken));
  const fileWait=await op('file.wait_change',()=>s.file.waitChange(file.id,fileInspect.revisionToken,5000));
  const delta1=await op('world.delta.after-file',()=>s.world.delta(world0.cursor,200));
  const renamed=await op('file.rename',()=>s.file.rename(file.id,`${workspace}/config-renamed.json`));
  const renamedInspect=await op('file.inspect.after-rename',()=>s.file.inspect(file.id));if(renamedInspect.fileId!==file.id||renamedInspect.identity.fileId128!==file.identity.fileId128)throw new Error('same-volume rename lost physical identity');
  await op('process.terminate.first.root',()=>s.process.terminate(first.process.id));
  await op('process.wait.first.root',()=>s.process.wait(first.process.id,5000));
  await op('network.wait_absent.first',()=>s.network.waitAbsent('127.0.0.1',ready1.port,listener1.id,10000));
  await op('job.members.after-first-exit',()=>s.job.members(job.id));
  const second=await op('job.start.second',()=>s.job.start(job.id,node,['X:/SHELLeye/repo/tests/fixtures/PersistentWorkload/server.js','--config',renamedInspect.path,'--port','0'],'X:/SHELLeye/repo'));
  const ready2Wait=await op('job.wait_output.ready.second',()=>s.job.waitOutput(job.id,'"type":"ready"',output1.cursor,15000));
  const ready2=JSON.parse(ready2Wait.record.text.trim());
  await op('job.wait_members.second',()=>s.job.waitMembers(job.id,2,15000));
  const members2=await op('job.members.second',()=>s.job.members(job.id));
  const root2=await op('process.inspect.second.root',()=>s.process.inspect(second.process.id));if(root2.processId===root1.processId)throw new Error('replacement process rebound first proc_*');
  const listener2=await op('network.wait_listener.second',()=>s.network.waitListener('127.0.0.1',ready2.port,second.process.id,10000));if(listener2.id===listener1.id)throw new Error('replacement listener rebound first listener_*');
  await op('listener.inspect.second',()=>s.listener.inspect(listener2.id));
  const service=await op('service.inspect.EventLog',()=>s.service.inspect('EventLog'));
  const listing=await op('directory.list.final',()=>s.directory.list(dir.id));
  const output2=await op('job.output.final',()=>s.job.output(job.id,ready2Wait.cursor,65536));
  const rawResult=await op('raw.exec.whoami',()=>r.exec('whoami',10000));if(rawResult.exitCode!==0||!rawResult.stdout.toLowerCase().includes('stealtheye'))throw new Error('raw escape hatch failed');
  const sync=await op('world.sync',()=>s.world.sync());
  await op('job.terminate',()=>s.job.terminate(job.id));
  await op('job.wait_empty',()=>s.job.waitEmpty(job.id,10000));
  await op('network.wait_absent.second',()=>s.network.waitAbsent('127.0.0.1',ready2.port,listener2.id,10000));
  const deltaFinal=await op('world.delta.final',()=>s.world.delta(world0.cursor,200));
  await op('file.delete',()=>s.file.delete(file.id));cleanup.file=true;
  await op('directory.delete',()=>client.request('file.delete',{fileId:dir.id},10000));cleanup.directory=true;
  const health=await op('state.health',()=>s.state.health());
  if(count<40)throw new Error(`typed operation count ${count} below threshold`);
  const result={passed:true,completedUtc:new Date().toISOString(),oneProgramHostInvocation:true,onePersistentConnection:true,typedOperationCount:count,modelCallsBetweenPrimitives:0,domains:['machine','session','volume','directory','file','process','job','network','service','powershell','world','raw','state'],machine:{id:machine.machineId,bootEpoch:machine.bootEpoch},job:{id:job.id,firstProcess:first.process.id,secondProcess:second.process.id,newProcess:first.process.id!==second.process.id},file:{id:file.id,sameIdentityAcrossRename:renamedInspect.identity.fileId128===file.identity.fileId128,finalPath:renamedInspect.path},listeners:{first:listener1.id,second:listener2.id,newListener:listener1.id!==listener2.id},powershell:{provider:ps.provider,engineVersion:ps.engineVersion,providerEpoch:ps.providerEpoch,structured:ps.structured,typeNames:ps.objects[0].typeNames,properties:ps.objects[0].properties},resourceSample:resources,service:{id:service.id,name:service.name,state:service.state,processId:service.processId},waits:{clientExit:clientWait.state,fileChanged:fileWait.changed,jobEmpty:true},deltas:{firstCount:delta1.deltas.length,finalCount:deltaFinal.deltas.length,types:[...new Set(deltaFinal.deltas.map(x=>x.type))]},output:{firstCursor:ready1Wait.cursor,secondCursor:ready2Wait.cursor,finalCursor:output2.cursor},raw:{exitCode:rawResult.exitCode,stdout:rawResult.stdout.trim()},health,cleanup,operationTrace:trace};
  fs.writeFileSync(`${results}/milestone-d.json`,JSON.stringify(result,null,2));console.log(JSON.stringify({...result,operationTrace:undefined}));
 }catch(e){try{cleanup.error=e.message}catch{};throw e}finally{await client.close();}
})().catch(e=>{console.error(e.stack||String(e));process.exit(1)});
